spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinemax_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Bangkok
    username: root
    password: 753951
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  secret: MOVEEKSECRETKEYMOVEEKSECRETKEYMOVEEK123456789
  expiration: 86400000

logging:
  level:
    org:
      springframework:
        security: DEBUG

file:
  upload-dir: ./uploads
